In [3]:
import numpy as np
import pandas as pd
import tensorflow as tf
from keras.layers import Dropout

In [4]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [5]:
dataset

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

# # Encoding categorical data
#### Label Encoding the "Gender" column

In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])
print(X)


[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [7]:
# One Hot Encoding the "Geography" column
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [8]:
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [10]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [8]:
X_train

array([[-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
        -1.03227043,  0.32472465]])

# Part 2 - Building the ANN

In [11]:
import keras

In [40]:
from keras.models import Sequential
from keras.layers import Dense


In [41]:
# Initializing the ANN
ann = tf.keras.models.Sequential()


In [42]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))


In [43]:
ann.add(Dropout(rate=0.1))#drop out pour améliorer l'ann bieé et variance

In [44]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [45]:
ann.add(Dropout(rate=0.1))

In [46]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [47]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [48]:
ann.fit(X_train, y_train, batch_size = 10, epochs = 100)

Epoch 1/100
800/800 [==============================] - 1s 1ms/step - loss: 0.5157 - accuracy: 0.7719
Epoch 2/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4614 - accuracy: 0.7994
Epoch 3/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4376 - accuracy: 0.8059
Epoch 4/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4233 - accuracy: 0.8121
Epoch 5/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4089 - accuracy: 0.8135
Epoch 6/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4053 - accuracy: 0.8136
Epoch 7/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4030 - accuracy: 0.8140
Epoch 8/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3966 - accuracy: 0.8158
Epoch 9/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3932 - accuracy: 0.8145
Epoch 10/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3935 - accura

KeyboardInterrupt: 

In [ ]:
# Predicting the Test set results
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

In [94]:
# Predicting the Test set results
y_pred = ann.predict(X_test)

63/63 [==============================] - 0s 917us/step


In [99]:
print(y_pred)

[[False]
 [False]
 [False]
 ...
 [False]
 [False]
 [False]]


In [100]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1488  107]
 [ 186  219]]


0.8535

# prédiction 

In [103]:
new_pred=ann.predict(sc.transform(np.array([[1.0,0.0,0.0,600,1,40,3,60000,2,1,1,50000]])))
new_pred=(new_pred>0.5)

1/1 [==============================] - 0s 23ms/step


In [104]:
print(new_pred)

[[False]]


# évaluer l'ann


In [25]:
from keras.wrappers.scikit_learn import KerasClassifier

from sklearn.model_selection import cross_val_score

In [26]:
def build_classifier():
    ann = tf.keras.models.Sequential()
    ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
    ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
    ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))
    ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return ann



In [20]:
ann =KerasClassifier(build_fn=build_classifier, batch_size = 10, epochs = 100)
precisions=cross_val_score(estimator=ann,X=X_train,y=y_train,cv=10)#n_jobs=-1)#pour utiliser tt les couer

Epoch 1/100


C:\Users\yazid\AppData\Local\Temp\ipykernel_14712\4157026621.py:1: DeprecationWarning: KerasClassifier is deprecated, use Sci-Keras (https://github.com/adriangb/scikeras) instead. See https://www.adriangb.com/scikeras/stable/migration.html for help migrating.
  ann =KerasClassifier(build_fn=build_classifier, batch_size = 10, epochs = 100)


720/720 [==============================] - 1s 1ms/step - loss: 0.5061 - accuracy: 0.7858
Epoch 2/100
720/720 [==============================] - 1s 1ms/step - loss: 0.4463 - accuracy: 0.7971
Epoch 3/100
720/720 [==============================] - 1s 1ms/step - loss: 0.4343 - accuracy: 0.7971
Epoch 4/100
720/720 [==============================] - 1s 1ms/step - loss: 0.4263 - accuracy: 0.7971
Epoch 5/100
720/720 [==============================] - 1s 1ms/step - loss: 0.4207 - accuracy: 0.8042
Epoch 6/100
720/720 [==============================] - 1s 1ms/step - loss: 0.4155 - accuracy: 0.8249
Epoch 7/100
720/720 [==============================] - 1s 1ms/step - loss: 0.4098 - accuracy: 0.8301
Epoch 8/100
720/720 [==============================] - 1s 1ms/step - loss: 0.4044 - accuracy: 0.8307
Epoch 9/100
720/720 [==============================] - 1s 1ms/step - loss: 0.3984 - accuracy: 0.8328
Epoch 10/100
720/720 [==============================] - 1s 1ms/step - loss: 0.3923 - accuracy: 0.8347
E

720/720 [==============================] - 1s 2ms/step - loss: 0.3372 - accuracy: 0.8622
Epoch 61/100
720/720 [==============================] - 1s 2ms/step - loss: 0.3369 - accuracy: 0.8615
Epoch 62/100
720/720 [==============================] - 1s 2ms/step - loss: 0.3373 - accuracy: 0.8614
Epoch 63/100
720/720 [==============================] - 1s 2ms/step - loss: 0.3369 - accuracy: 0.8606
Epoch 64/100
720/720 [==============================] - 1s 2ms/step - loss: 0.3367 - accuracy: 0.8632
Epoch 65/100
720/720 [==============================] - 1s 2ms/step - loss: 0.3366 - accuracy: 0.8614
Epoch 66/100
720/720 [==============================] - 1s 2ms/step - loss: 0.3361 - accuracy: 0.8618
Epoch 67/100
720/720 [==============================] - 1s 2ms/step - loss: 0.3356 - accuracy: 0.8614
Epoch 68/100
720/720 [==============================] - 1s 2ms/step - loss: 0.3361 - accuracy: 0.8610
Epoch 69/100
720/720 [==============================] - 1s 2ms/step - loss: 0.3362 - accuracy: 

720/720 [==============================] - 1s 2ms/step - loss: 0.3547 - accuracy: 0.8544
Epoch 19/100
720/720 [==============================] - 1s 2ms/step - loss: 0.3514 - accuracy: 0.8578
Epoch 20/100
720/720 [==============================] - 1s 2ms/step - loss: 0.3495 - accuracy: 0.8578
Epoch 21/100
720/720 [==============================] - 1s 2ms/step - loss: 0.3470 - accuracy: 0.8556
Epoch 22/100
720/720 [==============================] - 1s 2ms/step - loss: 0.3448 - accuracy: 0.8582
Epoch 23/100
720/720 [==============================] - 1s 2ms/step - loss: 0.3436 - accuracy: 0.8589
Epoch 24/100
720/720 [==============================] - 1s 2ms/step - loss: 0.3416 - accuracy: 0.8597
Epoch 25/100
720/720 [==============================] - 1s 2ms/step - loss: 0.3415 - accuracy: 0.8583
Epoch 26/100
720/720 [==============================] - 1s 2ms/step - loss: 0.3398 - accuracy: 0.8596
Epoch 27/100
720/720 [==============================] - 1s 2ms/step - loss: 0.3387 - accuracy: 

720/720 [==============================] - 1s 1ms/step - loss: 0.3395 - accuracy: 0.8624
Epoch 78/100
720/720 [==============================] - 1s 1ms/step - loss: 0.3397 - accuracy: 0.8649
Epoch 79/100
720/720 [==============================] - 1s 1ms/step - loss: 0.3391 - accuracy: 0.8640
Epoch 80/100
720/720 [==============================] - 1s 1ms/step - loss: 0.3394 - accuracy: 0.8642
Epoch 81/100
720/720 [==============================] - 1s 1ms/step - loss: 0.3392 - accuracy: 0.8631
Epoch 82/100
720/720 [==============================] - 1s 1ms/step - loss: 0.3390 - accuracy: 0.8657
Epoch 83/100
720/720 [==============================] - 1s 2ms/step - loss: 0.3395 - accuracy: 0.8621
Epoch 84/100
720/720 [==============================] - 1s 2ms/step - loss: 0.3392 - accuracy: 0.8640
Epoch 85/100
720/720 [==============================] - 1s 2ms/step - loss: 0.3391 - accuracy: 0.8625
Epoch 86/100
720/720 [==============================] - 1s 2ms/step - loss: 0.3387 - accuracy: 

720/720 [==============================] - 1s 1ms/step - loss: 0.3414 - accuracy: 0.8611
Epoch 36/100
720/720 [==============================] - 1s 1ms/step - loss: 0.3410 - accuracy: 0.8608
Epoch 37/100
720/720 [==============================] - 1s 2ms/step - loss: 0.3404 - accuracy: 0.8635
Epoch 38/100
720/720 [==============================] - 1s 2ms/step - loss: 0.3401 - accuracy: 0.8631
Epoch 39/100
720/720 [==============================] - 1s 2ms/step - loss: 0.3394 - accuracy: 0.8607
Epoch 40/100
720/720 [==============================] - 1s 2ms/step - loss: 0.3396 - accuracy: 0.8646
Epoch 41/100
720/720 [==============================] - 1s 2ms/step - loss: 0.3390 - accuracy: 0.8629
Epoch 42/100
720/720 [==============================] - 1s 2ms/step - loss: 0.3392 - accuracy: 0.8603
Epoch 43/100
720/720 [==============================] - 1s 2ms/step - loss: 0.3384 - accuracy: 0.8625
Epoch 44/100
720/720 [==============================] - 1s 2ms/step - loss: 0.3386 - accuracy: 

720/720 [==============================] - 1s 2ms/step - loss: 0.3273 - accuracy: 0.8662
Epoch 95/100
720/720 [==============================] - 1s 2ms/step - loss: 0.3270 - accuracy: 0.8674
Epoch 96/100
720/720 [==============================] - 1s 2ms/step - loss: 0.3268 - accuracy: 0.8656
Epoch 97/100
720/720 [==============================] - 1s 2ms/step - loss: 0.3273 - accuracy: 0.8636
Epoch 98/100
720/720 [==============================] - 1s 2ms/step - loss: 0.3274 - accuracy: 0.8653
Epoch 99/100
720/720 [==============================] - 1s 2ms/step - loss: 0.3274 - accuracy: 0.8644
Epoch 100/100
80/80 [==============================] - 0s 1ms/step - loss: 0.3621 - accuracy: 0.8487
Epoch 1/100
720/720 [==============================] - 2s 2ms/step - loss: 0.4769 - accuracy: 0.7935
Epoch 2/100
720/720 [==============================] - 1s 2ms/step - loss: 0.4419 - accuracy: 0.7960
Epoch 3/100
720/720 [==============================] - 1s 2ms/step - loss: 0.4307 - accuracy: 0.80

720/720 [==============================] - 1s 2ms/step - loss: 0.3374 - accuracy: 0.8643
Epoch 53/100
720/720 [==============================] - 1s 2ms/step - loss: 0.3377 - accuracy: 0.8633
Epoch 54/100
720/720 [==============================] - 1s 2ms/step - loss: 0.3369 - accuracy: 0.8654
Epoch 55/100
720/720 [==============================] - 1s 2ms/step - loss: 0.3372 - accuracy: 0.8636
Epoch 56/100
720/720 [==============================] - 1s 2ms/step - loss: 0.3372 - accuracy: 0.8639
Epoch 57/100
720/720 [==============================] - 1s 2ms/step - loss: 0.3371 - accuracy: 0.8650
Epoch 58/100
720/720 [==============================] - 1s 2ms/step - loss: 0.3364 - accuracy: 0.8653
Epoch 59/100
720/720 [==============================] - 1s 2ms/step - loss: 0.3372 - accuracy: 0.8646
Epoch 60/100
720/720 [==============================] - 1s 2ms/step - loss: 0.3363 - accuracy: 0.8639
Epoch 61/100
720/720 [==============================] - 1s 2ms/step - loss: 0.3370 - accuracy: 

In [21]:
print(precisions)

[0.85874999 0.85500002 0.88249999 0.85624999 0.8725     0.85624999
 0.86250001 0.84875    0.85000002 0.86250001]


In [13]:
print(precisions.mean())

NameError: name 'precisions' is not defined

In [ ]:
ecart_type=precisions.std()

# Améliorer l'ANN

In [24]:
#ann.add(Dropout(rate=0.1))

# Ajuster l'ann 

In [49]:
from keras.wrappers.scikit_learn import KerasClassifier

from sklearn.model_selection import GridSearchCV

In [50]:
def build_classifier(optimizer):
    ann = tf.keras.models.Sequential()
    ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
    ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
    ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))
    ann.compile(optimizer = optimizer, loss = 'binary_crossentropy', metrics = ['accuracy'])
    return ann

In [51]:
ann =KerasClassifier(build_fn=build_classifier)
parameters={"batch_size":[32,25],
            "epochs":[100],
            "optimizer":["adam","rmsprop"]
    
}
grid_search= GridSearchCV(estimator =ann,
                          param_grid = parameters,
                          scoring = "accuracy",
                          cv=5) 


C:\Users\yazid\AppData\Local\Temp\ipykernel_19380\536309113.py:1: DeprecationWarning: KerasClassifier is deprecated, use Sci-Keras (https://github.com/adriangb/scikeras) instead. See https://www.adriangb.com/scikeras/stable/migration.html for help migrating.
  ann =KerasClassifier(build_fn=build_classifier)


In [ ]:
grid_search = grid_search.fit(X_train,y_train)
best_parameters =grid_search.best_params_
best_precision = grid_search.best_score_

Epoch 1/100
200/200 [==============================] - 1s 1ms/step - loss: 0.5565 - accuracy: 0.7980
Epoch 2/100
200/200 [==============================] - 0s 1ms/step - loss: 0.4764 - accuracy: 0.7980
Epoch 3/100
200/200 [==============================] - 0s 1ms/step - loss: 0.4533 - accuracy: 0.7980
Epoch 4/100
200/200 [==============================] - 0s 1ms/step - loss: 0.4408 - accuracy: 0.7980
Epoch 5/100
200/200 [==============================] - 0s 1ms/step - loss: 0.4333 - accuracy: 0.7980
Epoch 6/100
200/200 [==============================] - 0s 1ms/step - loss: 0.4284 - accuracy: 0.7980
Epoch 7/100
200/200 [==============================] - 0s 1ms/step - loss: 0.4251 - accuracy: 0.7983
Epoch 8/100
200/200 [==============================] - 0s 1ms/step - loss: 0.4229 - accuracy: 0.8064
Epoch 9/100
200/200 [==============================] - 0s 1ms/step - loss: 0.4205 - accuracy: 0.8106
Epoch 10/100
200/200 [==============================] - 0s 1ms/step - loss: 0.4183 - accura

200/200 [==============================] - 0s 2ms/step - loss: 0.3419 - accuracy: 0.8636
Epoch 82/100
200/200 [==============================] - 0s 2ms/step - loss: 0.3420 - accuracy: 0.8644
Epoch 83/100
200/200 [==============================] - 0s 2ms/step - loss: 0.3418 - accuracy: 0.8648
Epoch 84/100
200/200 [==============================] - 0s 2ms/step - loss: 0.3416 - accuracy: 0.8642
Epoch 85/100
200/200 [==============================] - 0s 2ms/step - loss: 0.3418 - accuracy: 0.8653
Epoch 86/100
200/200 [==============================] - 0s 2ms/step - loss: 0.3412 - accuracy: 0.8641
Epoch 87/100
200/200 [==============================] - 0s 2ms/step - loss: 0.3416 - accuracy: 0.8625
Epoch 88/100
200/200 [==============================] - 0s 2ms/step - loss: 0.3412 - accuracy: 0.8633
Epoch 89/100
200/200 [==============================] - 0s 2ms/step - loss: 0.3417 - accuracy: 0.8647
Epoch 90/100
200/200 [==============================] - 0s 2ms/step - loss: 0.3412 - accuracy: 

200/200 [==============================] - 0s 2ms/step - loss: 0.3875 - accuracy: 0.8353
Epoch 62/100
200/200 [==============================] - 0s 2ms/step - loss: 0.3866 - accuracy: 0.8356
Epoch 63/100
200/200 [==============================] - 0s 2ms/step - loss: 0.3861 - accuracy: 0.8373
Epoch 64/100
200/200 [==============================] - 0s 2ms/step - loss: 0.3851 - accuracy: 0.8364
Epoch 65/100
200/200 [==============================] - 0s 2ms/step - loss: 0.3835 - accuracy: 0.8375
Epoch 66/100
200/200 [==============================] - 0s 2ms/step - loss: 0.3816 - accuracy: 0.8394
Epoch 67/100
200/200 [==============================] - 0s 2ms/step - loss: 0.3791 - accuracy: 0.8397
Epoch 68/100
200/200 [==============================] - 0s 2ms/step - loss: 0.3761 - accuracy: 0.8419
Epoch 69/100
200/200 [==============================] - 0s 2ms/step - loss: 0.3727 - accuracy: 0.8445
Epoch 70/100
200/200 [==============================] - 0s 2ms/step - loss: 0.3691 - accuracy: 

200/200 [==============================] - 0s 2ms/step - loss: 0.3456 - accuracy: 0.8594
Epoch 42/100
200/200 [==============================] - 0s 2ms/step - loss: 0.3454 - accuracy: 0.8580
Epoch 43/100
200/200 [==============================] - 0s 2ms/step - loss: 0.3450 - accuracy: 0.8587
Epoch 44/100
200/200 [==============================] - 0s 2ms/step - loss: 0.3450 - accuracy: 0.8584
Epoch 45/100
200/200 [==============================] - 0s 2ms/step - loss: 0.3449 - accuracy: 0.8583
Epoch 46/100
200/200 [==============================] - 0s 2ms/step - loss: 0.3446 - accuracy: 0.8578
Epoch 47/100
200/200 [==============================] - 0s 2ms/step - loss: 0.3443 - accuracy: 0.8569
Epoch 48/100
200/200 [==============================] - 0s 2ms/step - loss: 0.3443 - accuracy: 0.8583
Epoch 49/100
200/200 [==============================] - 0s 2ms/step - loss: 0.3442 - accuracy: 0.8577
Epoch 50/100
200/200 [==============================] - 0s 2ms/step - loss: 0.3440 - accuracy: 

In [ ]:
print(best_parameters)
print(best_precision)